#!/bin/bash

CONTAINER=hobbytaste_mongodb

function cleanup_container() {
    ./tasks/cleanup $CONTAINER;
}


# Set exit handlers
# Any other exit handler may be added to this function
function exit_handler() {
    cleanup_container;
}
trap exit_handler EXIT

echo "Running server..."
NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
