#!/bin/bash

CONTAINER=hobbytaste_mongodb

echo "Setting up DB..."
function cleanup_container() {
    ./tasks/cleanup $CONTAINER;
}
if ! docker start $CONTAINER 2>/dev/null
then
    docker pull mongo >/dev/null
    docker run -dp 27017:27017 --name $CONTAINER mongo >/dev/null

    echo DB container $CONTAINER
fi

echo "Loading fixtures..."
node tasks/fixtures.js >/dev/null

# Set exit handlers
function exit_handler() {
    cleanup_container;
}
trap exit_handler EXIT

echo "Running server..."
NODE_APP_INSTANCE=secrets NODE_ENV=test NODE_CONFIG_ENV=development TS_NODE_PROJECT='server/tsconfig.json' mocha --exit